/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

/**
 * @author usuario1
 */
public class VentanaEligeTerreno extends javax.swing.JFrame {
    private String ruta;
    private String[][] mapa;

    /**
     * Creates new form VentanaTerrenos
     */
    public VentanaEligeTerreno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ventanaCargaMapa = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(605, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cargar Mapa");

        ventanaCargaMapa.setPreferredSize(new java.awt.Dimension(623, 350));
        ventanaCargaMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaCargaMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ventanaCargaMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(233, 233, 233))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ventanaCargaMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public String[][] getMapa() {
        return mapa;
    }

    public void setMapa(String[][] mapa) {
        this.mapa = mapa;
    }

    private void ventanaCargaMapaActionPerformed(java.awt.event.ActionEvent evt) throws Error {//GEN-FIRST:event_ventanaCargaMapaActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser archivoSeleccionado = (JFileChooser) evt.getSource();
            String comando = evt.getActionCommand();
            File archivo = null;
            String linea = "";
            FileReader lector = null;
            BufferedReader lineas = null;
            List columnas = new ArrayList<>();

            if (comando.equals(JFileChooser.APPROVE_SELECTION)) {
                archivo = archivoSeleccionado.getSelectedFile();
                this.ruta = archivo.getAbsolutePath();

                lector = new FileReader(archivo);
                lineas = new BufferedReader(lector);

                this.mapa = lineas.lines().map((String line) -> {
                    String[] fila = line.split(",");

                    if (fila.length > 15) {
                        throw new Error("El numero de columnas es mayor a 15");
                    }

                    /*
                    for (var f : fila) {
                        System.out.println("algo " + f);
                    }
                    */


                    columnas.add(fila.length);
                    return fila;
                }).toArray((int size) -> new String[size][(int)columnas.get(0)]);

                if(this.mapa.length > 15) {
                    throw new Error("El numero de filas es mayor a 15 en el mapa");
                }

                final int referencia = (int)columnas.get(0);
                boolean esValido = columnas.stream().allMatch((var el) -> ((int)el) == referencia);

                if(!esValido) {
                    throw new Error("El mapa no es de NxM");
                }

                this.setVisible(false);
            } else if (comando.equals(JFileChooser.CANCEL_SELECTION)) {
                this.setVisible(false);
            }
        } catch (Error | FileNotFoundException error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", JOptionPane.ERROR_MESSAGE, null);
            System.out.println(error.getMessage());
        }

    }//GEN-LAST:event_ventanaCargaMapaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEligeTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEligeTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEligeTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEligeTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEligeTerreno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFileChooser ventanaCargaMapa;
    // End of variables declaration//GEN-END:variables
}
